### ISSUE TITLE
[BUG] Editing components in nodal loads

### ISSUE THREAD

**Issue by vit-smilauer** [janvorisek/edubeam#300]
There is a bug in editing components in nodal loads, development version. Create a few nodal load, go to menu Loads in the lower section. Try to change component value, for example Fx to number 5 kN. It fills 0.005 to the box, where should be 5 instead. The same bug exist for Element load.

Regards. Vit

**Comment by janvorisek** [comment]
@vit-smilauer It should be fixed. Can you check?

Note: use Ctrl+F5 and Ctrl+R in the online version to make sure latest version is loaded.
